-   id: pyre-check
    name: pyre-check
    description: ''
    entry: pyre-check
    language: python
    'types': [python]
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
